swagger: "2.0"
info:
  description: "An API for sending and receiving whatsapp messages seemlessly"
  version: "1.0.0"
  title: "One Route API"
  contact:
    email: "tunexlevel8@gmail.com"
host: "one-route-api.herokuapp.com"
tags:
  - name: "message"
    description: "Everything about messages"
  - name: "setup"
    description: "Setup phone number for messaging"
paths:
  /message:
    post:
      tags:
        - "message"
      summary: "Send a message to a whatsapp number"
      parameters:
        - in: "body"
          name: "body"
          description: "The content of the message"
          required: true
          schema:
            $ref: "#/definitions/Message"
      responses:
        "400":
          description: "Invalid response"
        "200":
          description: "Successful response"
  /{phone_no}/message:
    get:
      tags:
        - "message"
      summary: "Receive a message sent from your whatsapp number"
      parameters:
        - in: "path"
          name: "phone_no"
          description: "The phone number required"
          example: "2348069538862"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Invalid response"
        "200":
          description: "Successful response"
  /{phone_no}/interaction:
    get:
      tags:
        - "message"
      summary: "Receive all interactions for a phone number"
      parameters:
        - in: "path"
          name: "phone_no"
          description: "The phone number required"
          example: "2348069538862"
          required: true
          schema:
            type: "string"
        - in: "path"
          name: "start"
          description: "The page to start from"
          value: "0"
          schema:
            type: "integer"
        - in: "path"
          name: "limit"
          value: "10"
          description: "The maximun number of messages to display"
          schema:
            type: "integer"
      responses:
        "400":
          description: "Invalid response"
        "200":
          description: "Successful response"
  /template/message:
    post:
      tags:
        - "message"
      summary: "Send a message to a whatsapp number using a template"
      parameters:
        - in: "query"
          name: "name"
          description: "The name of the template"
          example: "first_welcome_messsage"
          required: true
          schema:
            type: "string"
        - in: "query"
          name: "message"
          description: "The content of the message"
          required: true
          schema:
            type: "string"
        - in: "query"
          name: "phone_no"
          description: "The content of the message"
          required: true
          schema:
            type: "string"
        
      responses:
        "400":
          description: "Invalid response"
        "200":
          description: "Successful response"
  /setup:
    post:
      tags:
        - "setup"
      summary: "Create a setup for a phone number"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Setup"
      responses:
        "400":
          description: "Invalid response"
        "200":
          description: "Successful response"
    put:
      tags:
        - "setup"
      summary: "Update a setup of a phone number"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Setup"
      responses:
        "400":
          description: "Invalid response"
        "200":
          description: "Successful response"
  /{phone_no}/setup:
    delete:
      tags:
        - "setup"
      summary: "Delete a setup of a phone number"
      parameters:
        - in: "path"
          name: "phone_no"
          description: "The phone number to setup"
          example: "2348069538862"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Invalid response"
        "200":
          description: "Successful response"
    get:
      tags:
        - "setup"
      summary: "Fetch a setup details"
      parameters:
        - in: "path"
          name: "phone_no"
          description: "The phone number required"
          example: "2348069538862"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Invalid response"
        "200":
          description: "Successful response"
definitions:
  Message:
    type: "object"
    properties:
      phone_no:
        type: "string"
        description: "Phone number"
        example: "2348069538862"
      message:
        type: "string"
        example: "Gooday my friend!"
  Setup:
    type: "object"
    properties:
      key:
        type: "string"
        description: "The api key gotten from 360 whatsapp message"
        example: "Gnmns_380i"
      phone_no:
        type: "string"
        description: "Phone number"
        example: "2348069538862"